### ISSUE TITLE
Solution formatting error in challenge in lesson 03-starting-with-data

### ISSUE THREAD

**Issue by FlicAnderson** [nerc-esces/python-intermediate-esces#28]
During 18 May workshop during @wood-chris's teaching, we noticed an issue with the solution to question 3 in the "Summary Data" challenge solution.  

`~~ waves_df.groupby([‘Seastate’])[“Temperature”].describe() ~~` 

This should probabably display as `waves_df.groupby(['Seastate'])['Temperature'].describe()` - consistent quote marks that paste in without causing errors, and removing the tildes. 

Issue located at:
https://edcarp.github.io/python-intermediate-esces/03-starting-with-data/index.html#solution-to-3

**Comment by wood-chris** [comment]
Fixed by 05ebf96 :) (it was actually missing tildes, rather than having too many!)
