### ISSUE TITLE
Solution typo in 'Counting' challenge at 04-data-types-and-formats lesson

### ISSUE THREAD

**Issue by FlicAnderson** [nerc-esces/python-intermediate-esces#29]
Error located in Solution here: 
https://edcarp.github.io/python-intermediate-esces/04-data-types-and-format/index.html#counting
Discovered during the Data Analysis in Python session in the afternoon.

Problem: 
Dataset is incorrectly named `surveys_df`, instead of `waves_df` in both answer options, causing errors. 

Additional improvement:
Alternative solution (not using a loop format) could also be added to show another (and really easy to read) way of finding the answer using chaining: 
`waves_df.isnull().sum()`

**Comment by wood-chris** [comment]
Fixed by 8d17cb081737aad28daa8eab64c4bb0309528813 :)
