### ISSUE TITLE
Incorrect axes on plot in lesson 07-pandas-matplotlib 

### ISSUE THREAD

**Issue by FlicAnderson** [nerc-esces/python-intermediate-esces#30]
Problem location: https://edcarp.github.io/python-intermediate-esces/07-pandas-matplotlib/index.html#link-matplotlib-and-pandas 

Problem: the title and axes on the plot generated from the code in the section labelled 'Link matplotlib and Panda' are incorrect and refer to another dataset (? ecology ?), rather than relating to the waves data used in this lesson.  

Suggested fix:
* `ax1.set_xlabel("Hindfoot length")` -> `ax1.set_xlabel('Tpeak: highest energy wave periodicity (in seconds')`    
* `fig.suptitle('Scatter plot of weight versus hindfoot length', fontsize=15)` -> `fig.suptitle('Scatter plot of Significant* Wave Height versus Tpeak', fontsize=15)`  

Additional Improvement: 
add `ax1.set_ylabel("Significant* Wave Height (Metres)")` to replace the automatically pulled in field name (adding units).

**Comment by wood-chris** [comment]
Fixed by 6a1afd62 :)
